/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 astronaut.gltf --transform
Author: nitwit.friends (https://sketchfab.com/nitwit.friends)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/astronaut-floating-in-space-8d486996594a4714be1adf0d20745aa4
Title: Astronaut floating in space
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Astronaut(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./img/astronaut-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <primitive object={nodes._rootJoint} />
        <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.Astronaut_mat} skeleton={nodes.Object_7.skeleton} scale={0.687} />
        <skinnedMesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.Astronaut_mat} skeleton={nodes.Object_8.skeleton} scale={0.687} />
        <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.Astronaut_mat} skeleton={nodes.Object_9.skeleton} scale={0.687} />
        <skinnedMesh name="Object_10" geometry={nodes.Object_10.geometry} material={materials['Mat.1']} skeleton={nodes.Object_10.skeleton} scale={0.687} />
        <skinnedMesh name="Object_11" geometry={nodes.Object_11.geometry} material={materials['Mat.4']} skeleton={nodes.Object_11.skeleton} scale={0.687} />
        <skinnedMesh name="Object_12" geometry={nodes.Object_12.geometry} material={materials['Mat.3']} skeleton={nodes.Object_12.skeleton} scale={0.687} />
        <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials['Mat.2']} skeleton={nodes.Object_13.skeleton} scale={0.687} />
      </group>
    </group>
  )
}

useGLTF.preload('/astronaut-transformed.glb')
